### ISSUE TITLE
Create the core of the project

### ISSUE THREAD

**Issue by alallema** [meilisearch/cloud-providers#11]
### Create the core of the project
Initialize the project by adding the needed tools:
- [x] .gitignore
- [x] LICENSE
- [x] bors
- [x] dependabot
- [x] ISSUE_TEMPLATE
- [x] meilisearch.pkr.hcl with only:
```
locals {
  timestamp = regex_replace(timestamp(), "[- TZ:]", "")
}

packer {
  required_plugins {
    amazon = {
      version = ">= 1.1.1"
      source = "github.com/hashicorp/amazon"
    }
  }
}
```

**Comment by brunoocasali** [comment]
@alallema I will let you try to add bors by yourself, ok? If you have any problems, let me know!
