### ISSUE TITLE
[AWS] Install SSM Agent to AWS AMI image

### ISSUE THREAD

**Issue by gmourier** [meilisearch/cloud-providers#32]
Hello 👋

I'm transferring a [feedback](https://github.com/meilisearch/product/discussions/576) initially created on the product repository since it seems better suited here. Let me know if it's not the case @alallema 🙏

"Please install AWS's SSM Agent so it would not require to open SSH port and manage SSH key. Would be able to use Session Manager instead and access management would be inside IAM permissions instead, which is way more secure."

**Comment by alallema** [comment]
As we no longer offer as much maintenance on this repo we don't plan to change the scripts for the time being by adding new functionality, the aim being to keep the images as simple as possible, as there are far too many options that can be added via AWS. I'm closing it
