### ISSUE TITLE
[AWS] How to add prefix url globally?

### ISSUE THREAD

**Issue by bannarisoftwares** [meilisearch/cloud-providers#33]
I have loadbalancer, currently we doing path based routing. I want to route the request from "api/search/*" path to ec2 instance. To match the pattern we need to add prefix url globally. So is any way available to add "api/search/" prefix url globally on meilisearch ec2?

**Comment by oluademola** [comment]
Hello @bannarisoftwares. Sorry for not getting back to you sooner. This isn't possible natively with meilisearch but have you tried using a reverse proxy like Nginx?

**Comment by alallema** [comment]
This issue has not been answered since, so I'm closing it. Feel free to reopen it if there is a problem
