### ISSUE TITLE
[AWS] Add cloudwatch agent to image to allow ssh-less access to logs

### ISSUE THREAD

**Issue by rweintraub-cycleon** [meilisearch/cloud-providers#35]
**Description**
In an usual deployment scenario you might be interested in the log files created by meilisearch. The current AMI does not include the cloudwatch agent & the documentation also does not include instruction on how to set-up the agent. As of now the only way to access those otherwise would be by ssh'ing into the machine which is not always encouraged.

**Basic example**
AWS provides a documentation that explains how the agent should be installed with valuable notes:
https://docs.aws.amazon.com/prescriptive-guidance/latest/implementing-logging-monitoring-cloudwatch/include-cloudwatch-agent-amis.html

**Comment by alallema** [comment]
As we no longer offer as much maintenance on this repo, I don't think this issue is still relevant. I'm closing it
