### ISSUE TITLE
Add packages to updates info in MOTD

### ISSUE THREAD

**Issue by fharper** [meilisearch/cloud-providers#40]
Based on previous discussions with @eskombro & @curquiza 

![image](https://user-images.githubusercontent.com/1170989/103570155-8fd39080-4e96-11eb-8dac-2ecafece08fe.png)

![image](https://user-images.githubusercontent.com/1170989/103570029-5b5fd480-4e96-11eb-8c74-da475efc279e.png)

**Comment by alallema** [comment]
This problem no longer seems relevant, I'm closing it
