### ISSUE TITLE
[AWS] - installation docs use debian which is not cost efficient

### ISSUE THREAD

**Issue by liesislukas** [meilisearch/cloud-providers#49]
please consider making AMI on graviton ec2, it's most cost efficient way to run memory intensive loads on aws: 

https://aws.amazon.com/ec2/graviton/  

https://aws.amazon.com/ec2/instance-types/x2g/

e.g. with curren AMI free tier on aws provide 1 cpu 1gb ram, with graviton it would provide double - 2cpu & 2gb ram. 

![image](https://user-images.githubusercontent.com/2733862/232026868-edd99ae0-d0ea-4ed1-8e29-994ba5b8a9f7.png)

![image](https://user-images.githubusercontent.com/2733862/232026991-2334ec4b-2238-40b3-9a0f-50dff7dee2c1.png)

**Comment by alallema** [comment]
As we no longer offer as much maintenance on this repo, I don't think this issue is still relevant. I'm closing it
