### ISSUE TITLE
[GCP] Issue with importing Image to GCP

### ISSUE THREAD

**Issue by derickdecesare** [meilisearch/cloud-providers#56]
**Description**
Running into an error when importing the meilisearch image to GCP. It looks like the error is coming from the image (not gcp). 

This happens about 12 minutes into importing the image from the URI provided by the meilisearch documentation: meilisearch-image/meilisearch-v1.0.2-debian-10.vmdk

**Expected behavior**
Successful import of the meilisearch image into GCP compute engine.

**Current behavior**
Error about 12 minutes in.

**Screenshots or Logs**
Last few lines of the logs:

[import-image]: 2023-07-14T14:47:57Z step "translate-disk" run error: step "wait-for-translator" run error: WaitForInstancesSignal FailureMatch found for "inst-translator-translate-translate-disk-r5qr1": "TranslateFailed: error: E: Sub-process /usr/bin/dpkg returned an error code (1)"
ERROR
ERROR: build step 0 "gcr.io/compute-image-tools/gce_vm_image_import:release" failed: step exited with non-zero status: 1

**Environment (please complete the following information):**
- OS: [e.g. Debian GNU/Linux]
I believe the image is using Debian? When importing I set to "Detect operation system" since the meilisearch documentation doesn't say to specify.

- Meilisearch version: [e.g. v.0.20.0]
v1.0.2

- cloud-providers version: [e.g v0.1.0]
Not sure what version this is

**Comment by alallema** [comment]
Hi @derickdecesare,
Thanks for raising this issue. Indeed, the GCP image seems to be broken. And yes the image is based on Debian

**Comment by matthiastjong** [comment]
+1 on this. What's the timeframe?

**Comment by sengkiq** [comment]
+1

**Comment by alallema** [comment]
Hi @derickdecesare,
I dig a little and if you deselect the `Install guest packages` it would work properly, I don't know why exactly for now.
I hope it will help
Also the last version available is the [meilisearch-v1-3-0-debian-11.vmdk](https://console.cloud.google.com/storage/browser/_details/meilisearch-image/meilisearch-v1-3-0-debian-11.vmdk?project=meilisearchimage)

**Comment by matthiastjong** [comment]
> 

Is there an up-to-date version list?

**Comment by alallema** [comment]
**Additional note in the problem-solving tenative:**
- Downgrading to Debian 10 doesn't solve the problem.
- Following the GCP documentation about [Guest Environment](https://cloud.google.com/compute/docs/images/install-guest-environment). I tried to add a check on the packer file:
    Code:
    ```
      provisioner "shell" {
        execute_command = "echo 'packer' | sudo -S sh -c '{{ .Vars }} {{ .Path }}'"
        inline = [
          "sudo apt update -y",
          "sudo apt upgrade -y",
          "sudo dpkg --configure -a",
          "sudo apt-get install -f -y",
          "wget https://storage.googleapis.com/compute-image-tools/release/linux/import_precheck -O import_precheck",
          "chmod +x import_precheck",
          "./import_precheck",
        ]
        only = ["googlecompute.debian"]
      }
    ```
    Logs:
    ```
      googlecompute.debian: The following packages will be upgraded:
      googlecompute.debian:   google-cloud-cli google-guest-agent
      googlecompute.debian: 2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
      googlecompute.debian: Need to get 165 MB of archives.
      googlecompute.debian: After this operation, 6667 kB of additional disk space will be used.
      googlecompute.debian: Get:1 https://packages.cloud.google.com/apt cloud-sdk-bullseye/main amd64 google-cloud-cli all 446.0.1-0 [153 MB]
      googlecompute.debian: Get:2 https://packages.cloud.google.com/apt google-compute-engine-bullseye-stable/main amd64 google-guest-agent amd64 1:20230913.00-g1 [11.8 MB]
      googlecompute.debian: apt-listchanges: Reading changelogs...
      googlecompute.debian: ########################################
      googlecompute.debian: # SHA2 Driver Signing Check -- SKIPPED #
      googlecompute.debian: ########################################
      googlecompute.debian:   * INFO: Only applicable on Windows 2008 systems.
      googlecompute.debian: ###############################
      googlecompute.debian: # Powershell Check -- SKIPPED #
      googlecompute.debian: ###############################
      googlecompute.debian:   * INFO: Not applicable on non-Windows systems.
      googlecompute.debian: ##############################
      googlecompute.debian: # OS Version Check -- PASSED #
      googlecompute.debian: ##############################
      googlecompute.debian:   * INFO: Detected system: debian-11
      googlecompute.debian: #######################
      googlecompute.debian: # SSH Check -- PASSED #
      googlecompute.debian: #######################
      googlecompute.debian:   * INFO: SSH (OpenSSH) detected on port 22.
      googlecompute.debian: #########################
      googlecompute.debian: # Disks Check -- PASSED #
      googlecompute.debian: #########################
      googlecompute.debian:   * INFO: root filesystem mounted on /dev/sda1
      googlecompute.debian:   * INFO: boot disk detected as /dev/sda
      googlecompute.debian:   * INFO: boot disk has valid GPT with protective MBR; using GPT.
      googlecompute.debian:   * INFO: GRUB detected
    ```

**Comment by alallema** [comment]
Hi @matthiastjong,
> Is there an up-to-date version list?

No, indeed, but you can access all the available images [here](https://console.cloud.google.com/storage/browser/meilisearch-image)
It could be useful to add it to the documentation page
