### ISSUE TITLE
[GCP] image bucket lacking permissions (storage.buckets.get)

### ISSUE THREAD

**Issue by Tarpsvo** [meilisearch/cloud-providers#58]
It seems like the gs://meilisearch-images bucket has restricted their permissions since I last used it. I no longer can create images from the disks in the bucket due to permission issues.

```
tarpsvo@cloudshell:~ (my-app)$ gcloud compute images import meilisearch-v130 --source-file=gs://meilisearch-image/meilisearch-v1-3-0-debian-11.vmdk

ERROR: (gcloud.compute.images.import) User [tarpsvo@github.com] does not have permission to access b instance [meilisearch-image] (or it may not exist): tarpsvo@github.com does not have storage.buckets.get access to the Google Cloud Storage bucket. Permission 'storage.buckets.get' denied on resource (or it may not exist).
```

I can run `gcloud storage ls gs://meilisearch-image` just fine, but GCP won't let me create images out of them.

Thanks!

**Comment by alallema** [comment]
Hi @Tarpsvo,
I rechecked the permission, and the bucket has only read access, but it has always been the case.
I still had a new access in case to the last image

**Comment by EmreAkkoc** [comment]
you should go to IAM & ADMIN select the service account of your compute engine after that give the roles
Storage Admin
Storage Object Admin
Storage Object Creator

**Comment by alallema** [comment]
Hi @EmreAkkoc,
It's already the case. But I redo it and create a new image in case:
[gs://meilisearch-image/meilisearch-v1-3-3-debian-11.vmdk](https://console.cloud.google.com/storage/browser/_details/meilisearch-image/meilisearch-v1-3-3-debian-11.vmdk?hl=en&project=meilisearchimage)
@Tarpsvo don't hesitate to tell me if it has change something 😊

**Comment by EmreAkkoc** [comment]
with the image u provided ([gs://meilisearch-image/meilisearch-v1-3-3-debian-11.vmdk](https://console.cloud.google.com/storage/browser/_details/meilisearch-image/meilisearch-v1-3-3-debian-11.vmdk?hl=en&project=meilisearchimage)

and given the roles
Storage Admin
Storage Object Admin
Storage Object Creator in IAM & ADMIN
it works, I managed to make it work and my instance worked perfectly in production as well

**Comment by alallema** [comment]
This issue seems resolved, so I'm closing it.
